services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "./src:/app"
    env_file:
      - ./.env
    depends_on:
      - postgres
      - rabbitmq
      - redis

  message_service:
    build: .
    volumes:
      - "./src:/app"
    command: celery -A tasks worker --loglevel=INFO
    depends_on:
      - postgres
      - rabbitmq
      - redis

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: billy
      POSTGRES_PASSWORD: billy
      POSTGRES_DB: billy
    ports:
      - "5432:5432"
    volumes:
      - "billy_psql_data:/var/lib/posgresql/data"

  rabbitmq:
    image: rabbitmq:4-management
    environment:
      RABBITMQ_DEFAULT_USER: billy
      RABBITMQ_DEFAULT_PASS: billy
    ports:
      - "15672:15672"

  redis:
    image: redis:8.4.0-alpine

volumes:
  billy_psql_data:

