services:
  app:
    build: .
    networks:
      - billy_network
    ports:
      - "8080:8080"
    volumes:
      - "./src:/app"
    env_file:
      - ./.env
    depends_on:
      - postgres
      - rabbitmq
      - redis

  async_tasks:
    build: .
    networks:
      - billy_network
    volumes:
      - "./src:/app"
    env_file:
      - ./.env
    depends_on:
      - postgres
      - rabbitmq
      - redis
    command: ["python", "-u", "async.py"]

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: billy
      POSTGRES_PASSWORD: billy
      POSTGRES_DB: billy
    networks:
      - billy_network
    ports:
      - "5432:5432"
    volumes:
      - "psql-data:/var/lib/postgresql/data"

  rabbitmq:
    image: rabbitmq:4-management
    environment:
      RABBITMQ_DEFAULT_USER: billy
      RABBITMQ_DEFAULT_PASS: billy
    networks:
      - billy_network
    ports:
      - "15672:15672"

  redis:
    image: redis:8.4.0-alpine
    networks:
      - billy_network

networks:
  billy_network:
    external: true

volumes:
  psql-data:
